### ISSUE TITLE
[BUG] Not all drives are recognised / not named recognisable

### ISSUE THREAD

**Issue by dflvunoooooo** [joshuar/go-hass-agent#142]
**Go Hass Agent Version**
7.3.1

**Describe the bug**
go-hass-agent seems to only create a sensor for one of my two drives. And interestingly this is the temperature of the second drive or sdb not sda. This sensor is named `HOSTNAME_drivetemp_temp1_temp`.

**To Reproduce**
Steps to reproduce the behaviour:
1. have two drives
2. start go-hass-agent

**Expected behaviour**
I would expect go-hass-agent to create two sensors. And it would be great, if the sensor represents the path or name of the drive.

**Logs**
[go-hass-agent.log](https://github.com/joshuar/go-hass-agent/files/15072710/go-hass-agent.log)

**Desktop (please complete the following information):**
 - OS: Linux
 - Distribution Proxmox
 - Version  6.2.16-4-pve

**Comment by joshuar** [comment]
Hey @dflvunoooooo, hmm, are both the drives the exact same make/model? The agent is using the Linux kernel [hwmon API for userspace](https://www.kernel.org/doc/html/latest/hwmon/sysfs-interface.html). So the hardware sensors are based off of whatever chips get exposed there. A device, like a hard drive or your CPU or graphics card, might expose zero or more chips. Each chip might have any number of sensors. The latter are what are exposed by the agent to Home Assistant.

To verify if the agent is missing a temp sensor for your sda drive, we could try some troubleshooting. Though the hwmon API is not the most featured API out there 😆

Firstly it might be worth checking the names of all the chips that are exposed:

```shell
cat /sys/class/hwmon/hwmon?/name
```

Note the names might be recognisable as a device, or could be something else. If you see one called `sda`, you've found the chips exposed by your drive.

_If you found a chip called sda:_

Note the directory under `/sys` that is listed, and you could then see if there are any files under those for temperature sensors:

```shell
ls /sys/class/hwmon/hwmonN/temp?_{input,label}
```
Replace `N` with the appropriate number. This will list out all the temp sensors that the agent will be able to read. Each temp sensor will have a `tempN_label` file containing its "name", used to derive the sensor name/id by the agent and a `tempN_input` file which is the actual reading/value. If you don't have both of those, then the device/chip doesn't have any temp sensors we can use.

_If you didn't find a chip called sda:_

It might be that the particular drive does not have a temp sensor, or it can't be exposed through hwmon for some reason. You can check the names of all temp sensors all chips are reporting with:

```shell
cat /sys/class/hwmon/hwmon?/temp?_label
```

This might help with correlating which chip is associated with your drives. You can then poke around in that directory to see if there is actually a temp sensor, it would need at least two files called `tempN_label` and `tempN_input` (where N is a number).

I do know that you might see a temp reported for this drive in other monitoring tools; they are likely using some other method to get it (like SMART attributes). I am planning on creating sensors for SMART attributes in the future. 

Hope this helps!

**Comment by dflvunoooooo** [comment]
Thank you for your very elaborate answer! 

I have a Western Digital red SSD and a HDD. The model is definitely different. But the chip as you call it under /sys/class/hwmon/ is twice called `drivetemp`. Maybe that is the problem. Should the chips realy be called `sda` and `sdb`?

Under `/sys/class/hwmon/hwmon2/temp1_input` and `/sys/class/hwmon/hwmon3/temp1_input` there are different temperatures reported and the model under `/sys/class/hwmon/hwmon2/device/model` and `/sys/class/hwmon/hwmon3/device/model` is also different.

I can get the temperature with S.M.A.R.T. via `smartctl -a /dev/sda | grep "Temperature"` and in the same way for sdb.

Interestingly `cat /sys/class/hwmon/hwmon?/temp?_label` does only report the temperatures of the CPU cores and some package. 
```
Package id 0
Core 0
Core 1
Core 2
Core 3
Core 4
Core 5
```

**Comment by joshuar** [comment]
Okay, this should be fixed in the next release by https://github.com/joshuar/go-hass-agent/commit/16f56dda42ca9d3d525c2d0d59446549a7a7c5b0. There is some background in the commit message.

This unfortunately required changing the naming format of all chips, so will result in new sensors being recorded in Home Assistant. 

The new naming convention will have a number appended to the chip name. So for example, where most Intel CPUs had a hwmon chip called "Coretemp", producing sensor names like "Coretemp Core 0 Temp", these will now be called "Coretemp 0 Core 0 Temp" (i.e., a number after "Coretemp"). Similar naming patterns are used for other chips. For example, for your two drives, there should now be several sensors with "Drivetemp 0 ..." and "Drivetemp 1 ..." prefixes.

Once you've installed the new release, you may want to remove the old sensors manually, under Developer Tools->Statistics in Home Assistant, for example. Or they can wait until they age out of the Home Assistant long-term statistics database automatically. Or, you can remove the agent from Home Assistant, wipe its config and then re-register it to remove any unused sensors.

**Comment by dflvunoooooo** [comment]
Great! Thank you for you fast work! And thank you for changing so much code. 

To represent sda or sdb is not possible with hwmon, I think. But couldn't the model under `/sys/class/hwmon/hwmon2/device/model` be used? For the drives this would represent the maker and had the benefit of knowing which of the numbered sensors is which.

**Comment by joshuar** [comment]
Good idea! I've implemented that. Here is a temp sensor for a disk in one of my machines:

![image](https://github.com/joshuar/go-hass-agent/assets/7401/d9bcbfd9-7906-44c0-8994-0bfcc50eef71)

This will be in the next version.

**Comment by dflvunoooooo** [comment]
Great, thank you for your work! I now have a sensor called `WDC WD100EFAX-68 Temp1`, but only the one. The second `WDC WDS500G1R0A` does not appear. Here is my log:

[go-hass-agent.log](https://github.com/joshuar/go-hass-agent/files/15143465/go-hass-agent.log)

**Comment by joshuar** [comment]
Hmm, on the system with the missing drive sensor, can you git clone the go-hass-agent source, then in the source directory, run:

```shell
go run pkg/linux/hwmon/examples/getAllSensors.go
```

This will print out all hwmon sensors and values, something like:

```
Acpitz 0 Temp1: 27.800 °C [Temp] (id: acpitz_0_temp_1, path: /sys/class/hwmon/hwmon0)
Iwlwifi 1 0 Temp1: 25.000 °C [Temp] (id: iwlwifi_1_0_temp_1, path: /sys/class/hwmon/hwmon5)
PM9A1 NVMe Samsung 1024GB Composite: 42.850 °C [Temp] (id: nvme_0_temp_1, path: /sys/class/hwmon/hwmon1) (crit: 84.850, max: 82.850, min: -273.150)
PM9A1 NVMe Samsung 1024GB Sensor 1: 42.850 °C [Temp] (id: nvme_0_temp_2, path: /sys/class/hwmon/hwmon1) (max: 65261.850, min: -273.150)
PM9A1 NVMe Samsung 1024GB Sensor 2: 46.850 °C [Temp] (id: nvme_0_temp_3, path: /sys/class/hwmon/hwmon1) (max: 65261.850, min: -273.150)
PM9A1 NVMe Samsung 1024GB Temp1 Alarm: 0.000  [Alarm] (id: nvme_0_temp_1_alarm, path: /sys/class/hwmon/hwmon1)
Dell Smm 0 Other: 69.000 °C [Temp] (id: dell_smm_0_temp_3, path: /sys/class/hwmon/hwmon3)
Dell Smm 0 Other: 32.000 °C [Temp] (id: dell_smm_0_temp_4, path: /sys/class/hwmon/hwmon3)
Dell Smm 0 Gpu: 40.000 °C [Temp] (id: dell_smm_0_temp_5, path: /sys/class/hwmon/hwmon3)
Dell Smm 0 Other: 50.000 °C [Temp] (id: dell_smm_0_temp_8, path: /sys/class/hwmon/hwmon3)
Dell Smm 0 Processor Fan: 5310.000 rpm [Fan] (id: dell_smm_0_fan_1, path: /sys/class/hwmon/hwmon3) (max: 5200.000, min: 5200.000, target: 5200.000)
Dell Smm 0 Motherboard Fan: 689.000 rpm [Fan] (id: dell_smm_0_fan_3, path: /sys/class/hwmon/hwmon3) (max: 3000.000, min: 0.000, target: 3000.000)
Dell Smm 0 Cpu: 54.000 °C [Temp] (id: dell_smm_0_temp_2, path: /sys/class/hwmon/hwmon3)
Dell Smm 0 Motherboard Fan: 718.000 rpm [Fan] (id: dell_smm_0_fan_2, path: /sys/class/hwmon/hwmon3) (max: 3000.000, min: 0.000, target: 3000.000)
Dell Smm 0 Ambient: 30.000 °C [Temp] (id: dell_smm_0_temp_6, path: /sys/class/hwmon/hwmon3)
Dell Smm 0 Other: 41.000 °C [Temp] (id: dell_smm_0_temp_7, path: /sys/class/hwmon/hwmon3)
Coretemp 0 Core 24: 42.000 °C [Temp] (id: coretemp_0_temp_26, path: /sys/class/hwmon/hwmon4) (max: 80.000, crit: 100.000)
Coretemp 0 Core 0: 44.000 °C [Temp] (id: coretemp_0_temp_2, path: /sys/class/hwmon/hwmon4) (max: 80.000, crit: 100.000)
Coretemp 0 Temp14 Alarm: 0.000  [Alarm] (id: coretemp_0_temp_14_alarm, path: /sys/class/hwmon/hwmon4)
Coretemp 0 Core 28: 44.000 °C [Temp] (id: coretemp_0_temp_30, path: /sys/class/hwmon/hwmon4) (crit: 100.000, max: 80.000)
Coretemp 0 Temp6 Alarm: 0.000  [Alarm] (id: coretemp_0_temp_6_alarm, path: /sys/class/hwmon/hwmon4)
Coretemp 0 Core 16: 42.000 °C [Temp] (id: coretemp_0_temp_18, path: /sys/class/hwmon/hwmon4) (max: 80.000, crit: 100.000)
Coretemp 0 Core 20: 45.000 °C [Temp] (id: coretemp_0_temp_22, path: /sys/class/hwmon/hwmon4) (max: 80.000, crit: 100.000)
Coretemp 0 Temp2 Alarm: 0.000  [Alarm] (id: coretemp_0_temp_2_alarm, path: /sys/class/hwmon/hwmon4)
Coretemp 0 Core 36: 41.000 °C [Temp] (id: coretemp_0_temp_38, path: /sys/class/hwmon/hwmon4) (crit: 100.000, max: 80.000)
Coretemp 0 Temp41 Alarm: 0.000  [Alarm] (id: coretemp_0_temp_41_alarm, path: /sys/class/hwmon/hwmon4)
Coretemp 0 Core 37: 41.000 °C [Temp] (id: coretemp_0_temp_39, path: /sys/class/hwmon/hwmon4) (crit: 100.000, max: 80.000)
Coretemp 0 Core 8: 44.000 °C [Temp] (id: coretemp_0_temp_10, path: /sys/class/hwmon/hwmon4) (crit: 100.000, max: 80.000)
Coretemp 0 Core 12: 43.000 °C [Temp] (id: coretemp_0_temp_14, path: /sys/class/hwmon/hwmon4) (max: 80.000, crit: 100.000)
Coretemp 0 Package Id 0: 45.000 °C [Temp] (id: coretemp_0_temp_1, path: /sys/class/hwmon/hwmon4) (max: 80.000, crit: 100.000)
Coretemp 0 Temp30 Alarm: 0.000  [Alarm] (id: coretemp_0_temp_30_alarm, path: /sys/class/hwmon/hwmon4)
Coretemp 0 Temp38 Alarm: 0.000  [Alarm] (id: coretemp_0_temp_38_alarm, path: /sys/class/hwmon/hwmon4)
Coretemp 0 Temp26 Alarm: 0.000  [Alarm] (id: coretemp_0_temp_26_alarm, path: /sys/class/hwmon/hwmon4)
Coretemp 0 Temp39 Alarm: 0.000  [Alarm] (id: coretemp_0_temp_39_alarm, path: /sys/class/hwmon/hwmon4)
Coretemp 0 Temp40 Alarm: 0.000  [Alarm] (id: coretemp_0_temp_40_alarm, path: /sys/class/hwmon/hwmon4)
Coretemp 0 Temp10 Alarm: 0.000  [Alarm] (id: coretemp_0_temp_10_alarm, path: /sys/class/hwmon/hwmon4)
Coretemp 0 Core 39: 41.000 °C [Temp] (id: coretemp_0_temp_41, path: /sys/class/hwmon/hwmon4) (crit: 100.000, max: 80.000)
Coretemp 0 Temp18 Alarm: 0.000  [Alarm] (id: coretemp_0_temp_18_alarm, path: /sys/class/hwmon/hwmon4)
Coretemp 0 Temp1 Alarm: 0.000  [Alarm] (id: coretemp_0_temp_1_alarm, path: /sys/class/hwmon/hwmon4)
Coretemp 0 Temp22 Alarm: 0.000  [Alarm] (id: coretemp_0_temp_22_alarm, path: /sys/class/hwmon/hwmon4)
Coretemp 0 Core 38: 41.000 °C [Temp] (id: coretemp_0_temp_40, path: /sys/class/hwmon/hwmon4) (crit: 100.000, max: 80.000)
Coretemp 0 Core 4: 41.000 °C [Temp] (id: coretemp_0_temp_6, path: /sys/class/hwmon/hwmon4) (crit: 100.000, max: 80.000)
Amdgpu 0 Fan1: 948.000 rpm [Fan] (id: amdgpu_0_fan_1, path: /sys/class/hwmon/hwmon2) (enable: 0.000, max: 3200.000, min: 0.000, target: 948.000)
Amdgpu 0 Sclk: 5000.000 Hz [Frequency] (id: amdgpu_0_freq_1, path: /sys/class/hwmon/hwmon2)
Amdgpu 0 Mclk: 96000.000 Hz [Frequency] (id: amdgpu_0_freq_2, path: /sys/class/hwmon/hwmon2)
Amdgpu 0 Ppt: 0.000 W [Power] (id: amdgpu_0_power_1, path: /sys/class/hwmon/hwmon2) (average: 16000.000, cap: 186000.000, cap_default: 186000.000, cap_max: 186000.000, cap_min: 174000.000)
Amdgpu 0 Pwm1: 0.000 Hz [PWM] (id: amdgpu_0_pwm_1, path: /sys/class/hwmon/hwmon2) (enable: 2.000, max: 255.000, min: 0.000)
Amdgpu 0 Junction: 56.000 °C [Temp] (id: amdgpu_0_temp_2, path: /sys/class/hwmon/hwmon2) (crit: 110.000, crit_hyst: -273.150, emergency: 115.000)
Amdgpu 0 Vddgfx: 0.862 V [Voltage] (id: amdgpu_0_in_0, path: /sys/class/hwmon/hwmon2)
Amdgpu 0 Edge: 50.000 °C [Temp] (id: amdgpu_0_temp_1, path: /sys/class/hwmon/hwmon2) (crit: 110.000, crit_hyst: -273.150, emergency: 115.000)
Amdgpu 0 Mem: 54.000 °C [Temp] (id: amdgpu_0_temp_3, path: /sys/class/hwmon/hwmon2) (crit: 105.000, crit_hyst: -273.150, emergency: 110.000)
{"level":"info","time":"2024-04-29T10:02:48+10:00","message":"Mem stats: alloc=6mb total_alloc=6mb sys=17mb heap_alloc=6mb heap_sys=11mb heap_idle=3mb heap_released=3mb heap_in_use=7mb stack_in_use=512kb stack_sys=512kb mspan_sys=95kb mcache_sys=30kb buck_hash_sys=1mb gc_sys=1mb other_sys=1mb mallocs_n=5342 frees_n=389 heap_objects_n=4953 gc_cpu_fraction=0.12"}
```

Can you paste that output here? From it, we should be able to see what is going on with the sensors.

**Comment by dflvunoooooo** [comment]
I ran into a version error. It is a proxmox sevrer, so it runs debian. It seems to want version 1.23
```
/home/kevin/go-hass-agent/go.mod:3: invalid go version '1.22.0': must match format 1.23
```
My go version seems to be 1.19
```
user@proxfuji:~$ go version
go version go1.19.8 linux/amd64
```

**Comment by joshuar** [comment]
Hey that's super interesting, that you get a different number of sensors when you run that, its the exact same code used by the agent! :confused: Do you get a different number of sensors each time you run it? Note the order they are displayed might change, as the chips are processed in parallel.

I think I can see the problem from the logs and this output. The sensor ID I generate, which is used as an entity ID in Home Assistant, is still not unique. I've got a code change that should fix this, though it'll break sensor output in Home Assistant again unfortunately. I'll circle back when it is committed. 

Side note: yeah I build with whatever is the latest and greatest Go version. You don't need Go installed to use the binaries, just for building. I use the official [Go installation instructions](https://go.dev/doc/install) rather than any package provided by my distro, which is often not the latest version. The build system also follows this installation method.

**Comment by dflvunoooooo** [comment]
That is strange. Does the path from which it is run matter? No, every time the same amount. But there are only the temperature sensors. go-hass-agent finds alto more sensors than just temperature sensors. 

I see, sorry to be the cause of so much headache. Thank you for your work!

Great, I followed that installation instructions too.

**Comment by joshuar** [comment]
That's super odd. I can't explain how the output of the command and the agent would differ. They are literally calling the exact same code :confused: It shouldn't matter where you run that command.

Anyway I have been refactoring the code so that it generates unique sensors for duplicate hardware drivers, like two hard drives both having a drivetemp driver listed, as you do.

Can you try out the latest [build artifacts from here](https://github.com/joshuar/go-hass-agent/actions/runs/8956329391)? **Please note, this build will create new entities in Home Assistant for all hardware sensors.** However, these builds should support the situation in this issue. 

Please grab whichever artifact you need for your architecture (amd64, arm or arm64). Inside the archive will all the packages for that architecture that would normally be included on the release page. So  you can pick whichever one you would normally use to upgrade an existing install.

With this build, you should see a bunch of "Hardware Sensor ..." sensors for various temp, fan, power etc. sensors. For those hard drives, you should see sensors named "WDC ... Temp ..." (i.e., named after the hard drive). 
 
I'm having trouble reproducing this problem locally, as none of my systems have multiple drivetemp sensors and I haven't worked out how I could artificially reproduce this scenario. But I do hope these artifacts either fix or move in the right direction.

**Comment by dflvunoooooo** [comment]
I don't know. Maybe I downloaded a different version or something. 

Awesome! This verion fixes the problem and both hdds are displayed with the modenumber, great work! 

![2024-05-06_12-40](https://github.com/joshuar/go-hass-agent/assets/32816598/44fc3edf-a191-4919-b3ef-808e1b8ee717)


The only "Hardware Sensor …" entities I see are for coretemp. I don't know if this is intended. I am sorry to be such a bother. But I am happy to help if I can and certainly test everything!

![2024-05-06_12-38](https://github.com/joshuar/go-hass-agent/assets/32816598/8add3052-8946-4ee1-961c-323bb5d0cafa)

**Comment by joshuar** [comment]
Brilliant! I'm glad we got to the bottom of this. Thank you for your patience and assistance resolving this and also for the suggestion to use the drive labels. I think the sensors look much nicer in Home Assistant now!

**Comment by dflvunoooooo** [comment]
Everything seems to be working, thank you!
