### ISSUE TITLE
[BUG] device gets overwritten from another one (identical hardware different hostname)

### ISSUE THREAD

**Issue by dflvunoooooo** [joshuar/go-hass-agent#148]
**Go Hass Agent Version**
8.0.0

**Describe the bug**
I tried to set up two raspberry pi 4s. The hardware is identical only the hostname is different. But everytime I register the second raspberry pi the old one in HA gets change to the hostname of that raspberry pi I recently tried to register. They have different tokens, to be sure. 

**To Reproduce**
Steps to reproduce the behaviour:
1. register the first raspberry pi.
2. register the second rasberry pi.
4. See the name in HA change from first to second.

**Expected behaviour**
I would expect a different entity to appear in HA. 

**Logs**
```
12:51PM DBG Debug logging enabled.
12:51PM INF Registration required. Starting registration process.
12:51PM INF Successfully registered agent.
12:51PM DBG Stopping agent.
```

**Desktop (please complete the following information):**
 - OS: Linux
 - Distribution Arch Linux Arm
 - Version 6.6.28-2-rpi

**Comment by joshuar** [comment]
That is super interesting. Can you look in the `~/.config/com.github.joshuar.go-hass-agent/preferences.toml` and see if the `device.id` preference is different on both of these machines?

**Comment by dflvunoooooo** [comment]
Thank you for your answer! Yes the id is indeed identical. Can I change it manually? As a workearound?

**Comment by joshuar** [comment]
Unfortunately, you can't change the ID after the agent has registered with Home Assistant. The Device ID is used by Home Assistant to identify individual devices and it would need to be changed in the Home Assistant database as well :frowning_face: 

It's super interesting that you've ended up with a duplicate though, as that shouldn't happen.  The underlying library the agent uses to get a device ID reads from the following files (in order, first one it can read from it uses):

- `/sys/class/dmi/id/product_uuid` (needs root permission to read)
- `/etc/machine-id`
- `/proc/sys/kernel/random/boot_id` (will always be unique each boot)

The agent doesn't run with privileges so the first file would never be used. Do you have a `/etc/machine-id` file and is it the same on both machines? Otherwise, is the `/proc/sys/kernel/random/boot_id` unique? 

Side note: If `/proc/sys/kernel/random/boot_id` is not unique, that might indicate some random number generator issues on the machine, or some kernel patching has deviated from the [documented behaviour](https://www.kernel.org/doc/html/latest/admin-guide/sysctl/kernel.html#random)  :worried: 

A workaround would be to just create a unique id manually and put in it `/etc/machine-id`. If you have a `/var/lib/dbus/machine-id` file, you can symlink that to `/etc/machine-id`. Or you could use `uuidgen` from _util-linux_ to generate a new one.

Once you are sure you have a unique device id in either /etc/machine-id or `/proc/sys/kernel/random/boot_id`, you can re-register the agent (`go-hass-agent register --force --terminal --host someserver --token sometoken`).

That would be my recommended workaround. 

I can't say if manually creating a `/etc/machine-id` might cause other issues with other things on the system. Likely however, if you don't have that file, you aren't using systemd and I would guess the other parts of the system don't need it if they are functioning already.

**Comment by dflvunoooooo** [comment]
That make sense. The file `/sys/class/dmi/id/product_uuid`  does not exist. The machine id is indeed identical. That may be, because I did set the system up on one raspberry pi and cloned the sd card to another card and simply changed the hostname. The `/proc/sys/kernel/random/boot_id` on the other hand is different on both raspberry pis. 

I removed the old file with `rm -f /etc/machine-id` and recreated it with `dbus-uuidgen --ensure=/etc/machine-id`. Then I registered both raspberry pis again, as you suggested. And it is working!

Side note: `/etc/machine-id` is not a systemd file, as discussed [here](https://unix.stackexchange.com/questions/402999/is-it-ok-to-change-etc-machine-id) at stackexchange. 

There is a force register option? Great! Till now I was deleting the config and reregistering. 

Thank you very much for your quick and helpful assistance!
