### ISSUE TITLE
[BUG] MQTT suspend suspends all connected clients

### ISSUE THREAD

**Issue by clinta** [joshuar/go-hass-agent#249]
**Go Hass Agent Version**
Go Hass Agent: v10.0.0

**Describe the bug**
If you have two computers running go-hass-agent connected to MQTT, pressing suspend on one of them suspends all of them. Because the MQTT button is not namespaced for the client.

**To Reproduce**
Steps to reproduce the behaviour:
1. Install go-hass-agent on two computers, and configure them for MQTT
2. Press suspend on the first computer

**Expected behaviour**
Only the computer chosen should suspend.

**Additional context**

It looks like every agent just listens for the "go_hass_agent_suspend" topic. They should listen to topics namespaced for the specific client. This is probably a bug for all MQTT commands, but I've only tested suspend.

**Comment by joshuar** [comment]
Oh dear, this is a PEBKAC, and by PEBKAC, I mean *I am the problem*. I changed part of the naming convetion for the entities for the power and session controls thinking "I don't need this bit of the name" but, in fact, I did need that part of the name to make it unique. Fixed with e77b9274aac249d6e1ddbc61457ed441c19c6a6c and I'll get a patch release out shortly.

Side note: this was also always a problem with the D-Bus command functionality, fixed with d403dbbe3867764cc43e014189b0ee4d5ad27f3e.

Thank you for reporting!

**Comment by eleektro** [comment]
Hi @joshuar,

Thanks for resolving the issue so quickly. I've reviewed the changes made to the code and I see that the topic has changed when publishing a command to D-Bus. I'm trying to send a notification from HAss, but I'm unable to do so—I get the following error:

```bash
WARN Error dispatching D-Bus command. linux.controller=mqtt controller=dbus_command bus=session destination=org.freedesktop.Notifications path=/org/freedesktop/Notifications method=org.freedesktop.Notifications.Notify error="SessionBus: call could not retrieve object (No such method 'Notify' in interface 'org.freedesktop.Notifications' at object path '/org/freedesktop/Notifications' (signature 'sdsssava{sv}d'))"
```

And this is the JSON message I'm publishing in the `gohassagent/<my-computer-name>/dbuscommand` topic:

```json
{
  "bus": "session",
  "path": "/org/freedesktop/Notifications",
  "method": "org.freedesktop.Notifications.Notify",
  "destination": "org.freedesktop.Notifications",
  "args": [
    "my-app-name",
    0,
    "my-icon",
    "summary",
    "body",
    [],
    {},
    5000
  ],
  "use_session_path": false
}
```

I think it might be that I'm not correctly typing the parameters for the Notify method. It works fine from a D-Bus explorer on my system.

Is it due to my incompetence, or could there be an issue mapping JSON values to Go's native types?

Thanks a lot, and sorry if I went off-topic too much.

**Comment by joshuar** [comment]
Hey @eleektro, I  believe this is a separate issue so I've moved the discussion over to #252. Let's discuss there.

**Comment by joshuar** [comment]
This issue should be closed by https://github.com/joshuar/go-hass-agent/commit/e77b9274aac249d6e1ddbc61457ed441c19c6a6c which is part of release [v10.0.1](https://github.com/joshuar/go-hass-agent/releases/tag/v10.0.1). I'm going to close this issue off but please re-open if you are still facing this issue.
