### ISSUE TITLE
[BUG] KDE Neon is reported as Debian Bookworm/Sid

### ISSUE THREAD

**Issue by Jay2645** [joshuar/go-hass-agent#72]
**Describe the bug**
When a computer is running `go-hass-agent` with KDE Neon, the distribution is instead reported as Debian Bookworm/Sid. (Neon is based on Ubuntu LTS.)

**To Reproduce**
1. Install `go-hass-agent` on a machine/VM running KDE Neon
2. Open Home Assistant
3. Look at the reported distribution

**Expected behavior**
The distribution should report KDE Neon.

**Screenshots**
![image](https://github.com/joshuar/go-hass-agent/assets/2058763/7eebc8cc-a4cf-4b16-90d2-634e08a6acd6)

**Logs**
[go-hass-app.log](https://github.com/joshuar/go-hass-agent/files/13806266/go-hass-app.log)

**Desktop (please complete the following information):**
 - OS: KDE neon 5.27 x86_64 (Kernel: 6.2.0-39-generic)
 - Browser: I suspect this template was made for a web dev, but I use Microsoft Edge (Chromium version)
 - Version: Version 120.0.2210.91 (Official build) (64-bit)

**Comment by joshuar** [comment]
This might be complicated to solve. I'm relying on the [github.com/shirou/gopsutil/v3/host](https://pkg.go.dev/github.com/shirou/gopsutil/v3/host) package to get the OS/distro information. From my grokking of the code it looks to preference getting the information from `/etc/debian_version` as opposed to other sources. I just spun up a KDE Neon live install and `/etc/debian_version` does report the Debian/bookworm info. 

So I'm pretty sure this is the same problem as say, this person on PopOS is having with the above library: https://github.com/shirou/gopsutil/issues/1469

I'd really like to avoid writing the code for this myself, because inevitably it might end up being a very big switch/else-if block that needs constant updating. Alternatively, I could just assume a canonical source like `/etc/os-release` and if a distro doesn't support that, it's gonna get "Unknown/Unknown" values. I will mention to the upstream library maintainer about whether adopting some hierarchy of places to get distro/version information would be good.

**Comment by joshuar** [comment]
I opened https://github.com/shirou/gopsutil/issues/1576 upstream for discussion as well.

**Comment by joshuar** [comment]
Hey there, just circling back that since v9 the distribution should be reported correctly. Please let me know if it is not reporting the correct values for you!

**Comment by Jay2645** [comment]
Hmm - just updated to see, and it's still reporting Sid for some reason:

![image](https://github.com/joshuar/go-hass-agent/assets/2058763/4623efdf-8258-439d-b6b4-2e89d4fec4f9)

**Comment by Jay2645** [comment]
I'm still on KDE Neon:

![image](https://github.com/joshuar/go-hass-agent/assets/2058763/415e2959-7c46-4530-ac40-0c34c799c593)

**Comment by joshuar** [comment]
Ugh, so I wrote code to get the correct values, but I didn't actually change those sensors to use it :facepalm: 

But that code wasn't enough, so I've refactored it and now it should be displaying the correct details in those sensors.

Can you try out the snapshot build from here:

https://github.com/joshuar/go-hass-agent/actions/runs/9218443179/artifacts/1533556590

This is an archive containing all the packages that would normally be on the release page (for amd64). It will effectively be the next release :crossed_fingers:  Please extract and use the appropriate one.

Let me know if this works correctly!

**Comment by joshuar** [comment]
Hey there, I expect that the latest version ([v9.4.0](https://github.com/joshuar/go-hass-agent/releases/tag/v9.4.0)) should fix this issue. Can you please try with that version and report back?

**Comment by joshuar** [comment]
Hey there, I'm going to close this issue on the assumption it is now fixed. Please try with the latest release and re-open if this is still an issue.

**Comment by Jay2645** [comment]
Hey! Sorry, work's been a PITA recently. It's fixed in 9.5 for sure. Thank you!
